# Generated by Django 6.0.2 on 2026-02-16 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-number'], 'verbose_name': 'ตอน', 'verbose_name_plural': 'ตอน'},
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['-created_at'], 'verbose_name': 'มังงะ', 'verbose_name_plural': 'มังงะ'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['number'], 'verbose_name': 'หน้า', 'verbose_name_plural': 'หน้า'},
        ),
        migrations.AddField(
            model_name='manga',
            name='category',
            field=models.CharField(choices=[('action', 'แอ็กชัน'), ('romance', 'โรแมนติก'), ('fantasy', 'แฟนตาซี'), ('drama', 'ดราม่า'), ('comedy', 'คอเมดี้'), ('horror', 'สยองขวัญ'), ('slice_of_life', 'ชีวิตประจำวัน'), ('other', 'อื่นๆ')], default='other', max_length=30, verbose_name='หมวดหมู่'),
        ),
        migrations.AddField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('ongoing', 'กำลังอัปเดต'), ('completed', 'จบแล้ว'), ('hiatus', 'พักตอน')], default='ongoing', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='reader.manga', verbose_name='มังงะ'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.FloatField(help_text='ตัวอย่าง: 1, 2, 10.5', verbose_name='ตอนที่'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='ชื่อตอน'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่อัปโหลด'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='cover',
            field=models.ImageField(upload_to='covers/', verbose_name='ภาพปก'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่มเรื่อง'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='description',
            field=models.TextField(blank=True, verbose_name='เรื่องย่อ'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.CharField(max_length=255, verbose_name='ชื่อเรื่อง'),
        ),
        migrations.AlterField(
            model_name='page',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='reader.chapter', verbose_name='ตอน'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to='pages/', verbose_name='รูปหน้า'),
        ),
        migrations.AlterField(
            model_name='page',
            name='number',
            field=models.PositiveIntegerField(verbose_name='ลำดับหน้า'),
        ),
    ]
