"""Add FeelFreePay fields to Transaction model

Revision ID: 22947681550a
Revises: fb0f72469c2f
Create Date: 2026-03-06 07:37:42.604314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '22947681550a'
down_revision: Union[str, None] = 'fb0f72469c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin_packages', 'stripe_price_id')
    op.add_column('transactions', sa.Column('ffp_reference_no', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('transactions', sa.Column('ffp_txn_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
    op.drop_constraint('transactions_stripe_session_id_key', 'transactions', type_='unique')
    op.create_index('uq_user_chapter_unlock', 'transactions', ['user_id', 'chapter_id'], unique=True, postgresql_where='chapter_id IS NOT NULL')
    op.create_unique_constraint(None, 'transactions', ['ffp_reference_no'])
    op.drop_column('transactions', 'stripe_payment_intent_id')
    op.drop_column('transactions', 'stripe_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('stripe_session_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_index('uq_user_chapter_unlock', table_name='transactions', postgresql_where='chapter_id IS NOT NULL')
    op.create_unique_constraint('transactions_stripe_session_id_key', 'transactions', ['stripe_session_id'])
    op.drop_column('transactions', 'ffp_txn_id')
    op.drop_column('transactions', 'ffp_reference_no')
    op.add_column('coin_packages', sa.Column('stripe_price_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
