"""Add unlocks_at to chapters

Revision ID: 2332c9f9e574
Revises: 82b127520226
Create Date: 2026-04-08 15:16:23.373427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2332c9f9e574'
down_revision: Union[str, None] = '82b127520226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('unlocks_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_chapters_unlocks_at'), 'chapters', ['unlocks_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapters_unlocks_at'), table_name='chapters')
    op.drop_column('chapters', 'unlocks_at')
    # ### end Alembic commands ###
