"""add sub_category

Revision ID: 9a0ca43bebef
Revises: f7a3d23d9638
Create Date: 2026-02-22 21:08:54.495389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a0ca43bebef'
down_revision: Union[str, None] = 'f7a3d23d9638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mangas', sa.Column('sub_category', sa.Enum('ACTION', 'ROMANCE', 'COMEDY', 'DRAMA', 'FANTASY', 'HORROR',
                  'SLICE_OF_LIFE', 'ISEKAI', 'SCHOOL', 'SCI_FI', 'OTHER', name='mangacategory'), server_default='OTHER', nullable=False))
    op.alter_column('mangas', 'is_visible',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_mangas_is_visible'),
                    'mangas', ['is_visible'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mangas_is_visible'), table_name='mangas')
    op.alter_column('mangas', 'is_visible',
                    existing_type=sa.BOOLEAN(),
                    nullable=True,
                    existing_server_default=sa.text('true'))
    op.drop_column('mangas', 'sub_category')
    # ### end Alembic commands ###
