"""add system_settings table for theme

Revision ID: f7a3d23d9638
Revises: 
Create Date: 2026-02-22 00:42:00.990315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7a3d23d9638'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'key',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sqlmodel.sql.sqltypes.AutoString(length=64),
                    existing_nullable=False)
    op.alter_column('system_settings', 'value',
                    existing_type=sa.VARCHAR(length=1024),
                    type_=sqlmodel.sql.sqltypes.AutoString(length=512),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'value',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(length=512),
                    type_=sa.VARCHAR(length=1024),
                    existing_nullable=False)
    op.alter_column('system_settings', 'key',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(length=64),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=False)
    # ### end Alembic commands ###
