"""Add last_chapter_updated_at to Manga

Revision ID: fb0f72469c2f
Revises: ed56348059c7
Create Date: 2026-02-24 08:34:00.968624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0f72469c2f'
down_revision: Union[str, None] = 'ed56348059c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mangas', sa.Column('last_chapter_updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_mangas_last_chapter_updated_at'), 'mangas', ['last_chapter_updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mangas_last_chapter_updated_at'), table_name='mangas')
    op.drop_column('mangas', 'last_chapter_updated_at')
    # ### end Alembic commands ###
